"""set ownership and grants for app role

Revision ID: 4185f6f685eb
Revises: 0b49e2bf85aa
Create Date: 2026-03-05 10:46:42.036591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4185f6f685eb'
down_revision: Union[str, Sequence[str], None] = '0b49e2bf85aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE case_event_type ADD VALUE IF NOT EXISTS 'STATUS_CHANGED';")
    # ---- change ownership ----
    op.execute("ALTER TABLE tenants OWNER TO app_owner;")
    op.execute("ALTER TABLE users OWNER TO app_owner;")
    op.execute("ALTER TABLE cases OWNER TO app_owner;")
    op.execute("ALTER TABLE case_events OWNER TO app_owner;")

    # ---- schema access ----
    op.execute("GRANT USAGE ON SCHEMA public TO app_user;")

    # ---- tenant + auth tables ----
    op.execute("GRANT SELECT, INSERT ON tenants TO app_user;")
    op.execute("GRANT SELECT, INSERT ON users TO app_user;")

    # ---- operational tables ----
    op.execute("GRANT SELECT, INSERT, UPDATE ON cases TO app_user;")
    op.execute("GRANT SELECT, INSERT ON case_events TO app_user;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # revoke permissions
    op.execute("REVOKE SELECT, INSERT ON tenants FROM app_user;")
    op.execute("REVOKE SELECT, INSERT ON users FROM app_user;")

    op.execute("REVOKE SELECT, INSERT, UPDATE ON cases FROM app_user;")
    op.execute("REVOKE SELECT, INSERT ON case_events FROM app_user;")

    op.execute("REVOKE USAGE ON SCHEMA public FROM app_user;")
    # ### end Alembic commands ###
