"""added case and case events

Revision ID: 5b6df6d193f9
Revises: 2a37263a67be
Create Date: 2026-03-04 21:54:05.438111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b6df6d193f9'
down_revision: Union[str, Sequence[str], None] = '2a37263a67be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='case_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_created_by'), 'cases', ['created_by'], unique=False)
    op.create_index(op.f('ix_cases_tenant_id'), 'cases', ['tenant_id'], unique=False)
    op.create_table('case_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('event_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.Enum('CASE_CREATED', 'EVIDENCE_COMPLETED', 'SCREENING_COMPLETED', 'APPROVED', name='case_event_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'case_id', 'idempotency_key', name='uq_case_event_idempotency')
    )
    op.create_index(op.f('ix_case_events_actor_id'), 'case_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_case_events_case_id'), 'case_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_events_tenant_id'), 'case_events', ['tenant_id'], unique=False)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    
    # --- RLS ---
    # Create RLS policies for cases
    op.execute("ALTER TABLE cases ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE cases FORCE ROW LEVEL SECURITY;")
    op.execute("""
    CREATE POLICY cases_tenant_isolation ON cases
    USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
    """)
    # Create RLS policies for case_events
    op.execute("ALTER TABLE case_events ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE case_events FORCE ROW LEVEL SECURITY;")
    op.execute("""
    CREATE POLICY case_events_tenant_isolation ON case_events
    USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
    """)

    # --- append-only enforcement for case_events ---
    # Block UPDATE and DELETE operations on case_events to enforce append-only behavior
    op.execute("""
    CREATE OR REPLACE FUNCTION prevent_case_events_mutation()
    RETURNS trigger AS $$
    BEGIN
      RAISE EXCEPTION 'case_events is append-only';
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER case_events_no_update
    BEFORE UPDATE ON case_events
    FOR EACH ROW EXECUTE FUNCTION prevent_case_events_mutation();
    """)

    op.execute("""
    CREATE TRIGGER case_events_no_delete
    BEFORE DELETE ON case_events
    FOR EACH ROW EXECUTE FUNCTION prevent_case_events_mutation();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # triggers + function
    op.execute("DROP TRIGGER case_events_no_delete ON case_events;")
    op.execute("DROP TRIGGER case_events_no_update ON case_events;")
    op.execute("DROP FUNCTION prevent_case_events_mutation;")
    # RLS policies
    op.execute("ALTER TABLE case_events DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE case_events NO FORCE ROW LEVEL SECURITY;")
    op.execute("DROP POLICY case_events_tenant_isolation ON case_events;")
    op.execute("ALTER TABLE cases DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE cases NO FORCE ROW LEVEL SECURITY;")
    op.execute("DROP POLICY cases_tenant_isolation ON cases;")
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_case_events_tenant_id'), table_name='case_events')
    op.drop_index(op.f('ix_case_events_case_id'), table_name='case_events')
    op.drop_index(op.f('ix_case_events_actor_id'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_index(op.f('ix_cases_tenant_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_by'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
